all:
	g++ main.cpp general_func.cpp                                                   \
                    class_r_vector/class_r_vector.cpp class_r_vector/operators.cpp  \
                    class_sys/class_sys.cpp class_kernel/class_kernel.cpp           \
                        -I"C:\Program Files\MinGW64\SFML-2.5.1\include"             \
                        -L"C:\Program Files\MinGW64\SFML-2.5.1\lib"                 \
                        -lsfml-graphics -lsfml-window -lsfml-system